name = "tg-chatbot"
compatibility_date = "2024-01-01"
account_id = "9e0813edc223ca6ab3853bc3453a67c0"
main = "src/index.ts"

[[kv_namespaces]]
binding = "TG_BOT_KV"
id = "4a838fa87b4243c0a10ef00fb0d287b3"

[vars]
TELEGRAM_TOKEN = "8449214105:AAFCKx9ddIe4vEmT3yrneMW7Wziw-JaAEHg"
GEMINI_API_KEY = ""
GROQ_API_KEY = "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"
ACCESS_MODE = "public"
ALLOWED_USER_IDS = ""
